#!/bin/bash 
MAX=599
echo "clear" > plot3D.gpi
echo "reset" >> plot3D.gpi

echo "set key center top">> plot3D.gpi
echo "set size ratio -1">> plot3D.gpi
echo "unset key">> plot3D.gpi
echo "set terminal gif animate delay 1" >> plot3D.gpi
echo "set output \"animate.gif\"" >> plot3D.gpi

# echo "unset border ; unset xtics ; unset ytics ; unset ztics " >> plot3D.gpi


	echo " L=5.93" >> plot3D.gpi
	echo "set xrange [ 0 : L ] noreverse nowriteback" >> plot3D.gpi
	echo "set yrange [ 0 : L ] noreverse nowriteback" >> plot3D.gpi
	echo "set zrange [ 0 : L ] noreverse nowriteback" >> plot3D.gpi


for i in `seq 0 ${MAX}`
do
echo "set title \"step : ${i}\" " \
>> plot3D.gpi
echo "splot 'prova.dat' index ${i} u 1:2:3  pt 7,'prova.dat' index ${i} using 1:2:3:5:6:7 with vectors head filled lt 1" \
>> plot3D.gpi
done
